name: pulltube
description: Personal iOS YouTube downloader with premium dark styling.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.5.3
  dio: ^5.9.2
  photo_manager: ^3.9.0
  permission_handler: ^11.4.0
  google_fonts: ^6.3.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  ffmpeg_kit_flutter_new: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
