//
//  Generated file. Do not edit.
//  This file is regenerated by `flutter pub get` — do not modify manually.
//

// clang-format off

#import "GeneratedPluginRegistrant.h"

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
}

@end
